apiVersion: v1
kind: ConfigMap
metadata:
  name: quakewatch-config
  namespace: quakewatch
  labels:
    app: quakewatch
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  LOG_LEVEL: "INFO"
  METRICS_ENABLED: "true"
  HEALTH_CHECK_ENABLED: "true"
  # Application specific configuration
  EARTHQUAKE_API_URL: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson"
  UPDATE_INTERVAL: "300"  # 5 minutes
  MAX_EARTHQUAKES: "100"
  # Monitoring configuration
  PROMETHEUS_METRICS_PORT: "5000"
  PROMETHEUS_METRICS_PATH: "/metrics"
