apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quakewatch
  namespace: quakewatch
  labels:
    release: monitoring           # חייב להתאים לשם ההתקנה של helm (monitoring)
spec:
  namespaceSelector:
    matchNames:
      - quakewatch
  selector:
    matchLabels:
      app: quakewatch             # חייב להתאים ל-label של ה-Service
  endpoints:
    - port: http                  # חייב להתאים לשם הפורט בשירות
      path: /metrics
      interval: 15s
