apiVersion: v1
kind: Service
metadata:
  name: quakewatch
  namespace: quakewatch
  labels:
    app: quakewatch
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  selector:
    app: quakewatch
  ports:
    - name: http       # חייב להתאים לשם שה-ServiceMonitor יבחר
      port: 80
      targetPort: 8080 # חייב להתאים ל-containerPort של ה-Deployment
