apiVersion: v1
kind: Service
metadata:
  name: quakewatch
  labels:
    app: quakewatch
spec:
  type: ClusterIP
  selector:
    app: quakewatch
  ports:
    - name: http
      port: 80
      targetPort: 80
