#!/bin/bash

# Grafana Dashboard Import Script
# This script helps you import the custom dashboards into Grafana

echo "🚀 Grafana Dashboard Import Helper"
echo "=================================="
echo ""
echo "📊 Available Dashboards:"
echo "1. QuakeWatch Application Dashboard"
echo "2. Kubernetes Cluster Health Dashboard" 
echo "3. System Overview Dashboard"
echo ""
echo "🔗 Access Grafana at: http://localhost:3000"
echo "👤 Username: admin"
echo "🔑 Password: prom-operator"
echo ""
echo "📋 Import Instructions:"
echo "1. Open Grafana in your browser"
echo "2. Click the '+' icon in the left sidebar"
echo "3. Select 'Import'"
echo "4. Choose one of the JSON files:"
echo "   - quakewatch-application-dashboard.json"
echo "   - cluster-health-dashboard.json"
echo "   - system-overview-dashboard.json"
echo "5. Click 'Load' and then 'Import'"
echo ""
echo "🎯 Dashboard Features:"
echo "✅ Real-time metrics from QuakeWatch"
echo "✅ Cluster health monitoring"
echo "✅ CPU, Memory, and Network usage"
echo "✅ Request rates and error tracking"
echo "✅ Earthquake data visualization"
echo "✅ Pod and service status"
echo ""
echo "🔧 Troubleshooting:"
echo "- If dashboards show 'No Data', check that Prometheus is scraping metrics"
echo "- Verify that the QuakeWatch app is running and exposing /metrics"
echo "- Check Prometheus targets at http://localhost:9090/targets"
echo ""
echo "📈 Dashboard URLs (after import):"
echo "- QuakeWatch App: http://localhost:3000/d/quakewatch-app"
echo "- Cluster Health: http://localhost:3000/d/cluster-health"
echo "- System Overview: http://localhost:3000/d/system-overview"
