{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}-quakewatch
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: quakewatch
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.serviceMonitor.spec.endpoints.interval | default "15s" }}
{{- end }}
